import type { DeepSeekToolDefinition } from "../../providers/deepseek/deepseek-adapter";

export const INSPECT_PDF_EDITABILITY_TOOL_NAME = "inspect_pdf_editability";
export const EDIT_SOURCE_BACKED_DOCUMENT_TOOL_NAME = "edit_source_backed_document";
export const EDIT_PDF_TOOL_NAME = "edit_pdf";
export const COMPARE_DOCUMENT_REVISIONS_TOOL_NAME = "compare_document_revisions";

const pageArray = { type: "array", items: { type: "integer", minimum: 1 }, minItems: 1, maxItems: 200 };
const operation = { oneOf: [
  { type: "object", additionalProperties: false, required: ["type", "pages"], properties: { type: { const: "delete_pages" }, pages: pageArray } },
  { type: "object", additionalProperties: false, required: ["type", "order"], properties: { type: { const: "reorder_pages" }, order: pageArray } },
  { type: "object", additionalProperties: false, required: ["type", "pages", "degrees"], properties: { type: { const: "rotate_pages" }, pages: pageArray, degrees: { type: "integer", enum: [90, 180, 270] } } },
  { type: "object", additionalProperties: false, required: ["type", "afterPage"], properties: { type: { const: "insert_blank_page" }, afterPage: { type: "integer", minimum: 0 }, width: { type: "number", minimum: 0 }, height: { type: "number", minimum: 0 } } },
  { type: "object", additionalProperties: false, required: ["type", "sourceDocumentId", "afterPage"], properties: { type: { const: "merge_document" }, sourceDocumentId: { type: "string" }, afterPage: { type: "integer", minimum: 0 } } },
  { type: "object", additionalProperties: false, required: ["type", "query"], properties: { type: { const: "redact_text" }, query: { type: "string", minLength: 1, maxLength: 4096 }, pages: pageArray, expectedOccurrences: { type: "integer", minimum: 0 } } },
  { type: "object", additionalProperties: false, required: ["type", "query", "replacement", "expectedOccurrences"], properties: { type: { const: "replace_text" }, query: { type: "string", minLength: 1, maxLength: 4096 }, replacement: { type: "string", maxLength: 16384 }, pages: pageArray, expectedOccurrences: { type: "integer", minimum: 0 }, fontSize: { type: "number", exclusiveMinimum: 0 } } },
  { type: "object", additionalProperties: false, required: ["type", "page", "x", "y", "width", "height", "text", "fontSize"], properties: { type: { const: "add_text" }, page: { type: "integer", minimum: 1 }, x: { type: "number", minimum: 0 }, y: { type: "number", minimum: 0 }, width: { type: "number", exclusiveMinimum: 0 }, height: { type: "number", exclusiveMinimum: 0 }, text: { type: "string", maxLength: 16384 }, fontSize: { type: "number", exclusiveMinimum: 0 }, align: { type: "string", enum: ["left", "center", "right"] } } },
  { type: "object", additionalProperties: false, required: ["type", "page", "imageId", "x", "y", "width", "height"], properties: { type: { const: "add_image" }, page: { type: "integer", minimum: 1 }, imageId: { type: "string" }, x: { type: "number", minimum: 0 }, y: { type: "number", minimum: 0 }, width: { type: "number", exclusiveMinimum: 0 }, height: { type: "number", exclusiveMinimum: 0 } } },
  { type: "object", additionalProperties: false, required: ["type", "text", "opacity"], properties: { type: { const: "watermark" }, text: { type: "string", minLength: 1, maxLength: 4096 }, opacity: { type: "number", minimum: 0, maximum: 1 }, pages: pageArray } },
  { type: "object", additionalProperties: false, required: ["type", "fieldName", "value"], properties: { type: { const: "set_form_field" }, fieldName: { type: "string", minLength: 1, maxLength: 512 }, value: { type: "string", maxLength: 16384 } } },
] };
export const PDF_EDIT_TOOL_DEFINITIONS: DeepSeekToolDefinition[] = [
  { type: "function", function: { name: INSPECT_PDF_EDITABILITY_TOOL_NAME, description: "Inspect an authorized PDF and report its actual editability and recommended method without changing it.", parameters: { type: "object", additionalProperties: false, required: ["documentId"], properties: { documentId: { type: "string" }, pages: { type: "array", items: { type: "integer", minimum: 1 }, maxItems: 100 } } } } },
  { type: "function", function: { name: EDIT_SOURCE_BACKED_DOCUMENT_TOOL_NAME, description: "Patch the saved source of a generated PDF, rerun its saved entrypoint, and create a child immutable revision.", parameters: { type: "object", additionalProperties: false, required: ["documentId", "baseRevisionId", "patches"], properties: { documentId: { type: "string" }, baseRevisionId: { type: "string" }, patches: { type: "array", minItems: 1, maxItems: 20, items: { type: "object", additionalProperties: false, required: ["type", "path"], properties: { type: { type: "string", enum: ["replace_text", "unified_diff"] }, path: { type: "string" }, oldText: { type: "string", maxLength: 65536 }, newText: { type: "string", maxLength: 65536 }, expectedOccurrences: { type: "integer", minimum: 0 }, patch: { type: "string", maxLength: 65536 } } } }, outputFilename: { type: "string" } } } } },
  { type: "function", function: { name: EDIT_PDF_TOOL_NAME, description: "Apply safe structural, redaction, overlay, form, watermark, or merge operations to an authorized PDF and create a new immutable revision.", parameters: { type: "object", additionalProperties: false, required: ["documentId", "operations"], properties: { documentId: { type: "string" }, operations: { type: "array", minItems: 1, maxItems: 30, items: operation }, outputFilename: { type: "string" } } } } },
  { type: "function", function: { name: COMPARE_DOCUMENT_REVISIONS_TOOL_NAME, description: "Compare two authorized document revisions by rendered page hashes and source hashes.", parameters: { type: "object", additionalProperties: false, required: ["projectId", "leftRevisionId", "rightRevisionId"], properties: { projectId: { type: "string" }, leftRevisionId: { type: "string" }, rightRevisionId: { type: "string" } } } } },
];

export function availablePdfEditTools(hasAuthorizedPdf: boolean) { return hasAuthorizedPdf ? PDF_EDIT_TOOL_DEFINITIONS : []; }
