"use client";

import { useEffect, useState } from "react";
import type { ConnectorCatalogItem, ConnectorConnection, ConnectorTool } from "../../lib/connector-protocol";
import { disconnectConnectorConnection, fetchConnectorConnections, fetchConnectorTools, refreshConnectorConnection, removeMcpServer, setDefaultConnectorConnection, startConnectorConnection, updateConnectorTool } from "./connectors-service";
import { ConnectorPermissions } from "./connector-permissions";

export function ConnectorDetailModal({ connector, onClose, onChanged }: { connector: ConnectorCatalogItem; onClose: () => void; onChanged: () => Promise<void> }) {
  const [connections, setConnections] = useState<ConnectorConnection[]>(connector.connections); const [tools, setTools] = useState<ConnectorTool[]>([]); const [error, setError] = useState(""); const [busy, setBusy] = useState(false);
  useEffect(() => { let active = true; void Promise.all([fetchConnectorConnections(connector.id), fetchConnectorTools(connector.id)]).then(([nextConnections, nextTools]) => { if (active) { setConnections(nextConnections); setTools(nextTools); } }).catch((reason) => { if (active) setError(reason instanceof Error ? reason.message : "Connector details could not be loaded."); }); return () => { active = false; }; }, [connector.id]);
  async function connect() { setBusy(true); setError(""); try { window.location.assign(await startConnectorConnection(connector.id)); } catch (reason) { setError(reason instanceof Error ? reason.message : "Connection could not start."); setBusy(false); } }
  async function disconnect(connectionId: string) { if (!window.confirm(`Disconnect ${connector.name}?`)) return; setBusy(true); setError(""); try { await disconnectConnectorConnection(connector.id, connectionId); setConnections((current) => current.filter((item) => item.id !== connectionId)); await onChanged(); } catch (reason) { setError(reason instanceof Error ? reason.message : "Connection could not be disconnected."); } finally { setBusy(false); } }
  async function refresh(connectionId: string) { setBusy(true); setError(""); try { await refreshConnectorConnection(connector.id, connectionId); setTools(await fetchConnectorTools(connector.id)); await onChanged(); } catch (reason) { setError(reason instanceof Error ? reason.message : "Tool discovery failed."); } finally { setBusy(false); } }
  async function changeTool(tool: ConnectorTool, enabled: boolean) { setBusy(true); try { await updateConnectorTool(connector.id, tool.name, { enabled }); setTools((current) => current.map((item) => item.name === tool.name ? { ...item, enabled } : item)); } catch (reason) { setError(reason instanceof Error ? reason.message : "Tool permission could not be changed."); } finally { setBusy(false); } }
  async function changeApproval(tool: ConnectorTool, approvalMode: "never" | "always") { setBusy(true); try { await updateConnectorTool(connector.id, tool.name, { approvalMode }); setTools((current) => current.map((item) => item.name === tool.name ? { ...item, approvalMode } : item)); } catch (reason) { setError(reason instanceof Error ? reason.message : "Approval preference could not be changed."); } finally { setBusy(false); } }
  async function remove() { if (!window.confirm(`Remove ${connector.name}?`)) return; setBusy(true); try { await removeMcpServer(connector.id); await onChanged(); onClose(); } catch (reason) { setError(reason instanceof Error ? reason.message : "MCP server could not be removed."); } finally { setBusy(false); } }
  return <div className="settings-submodal-backdrop" role="presentation" onMouseDown={(event) => { if (event.target === event.currentTarget) onClose(); }}><section className="settings-submodal connector-detail-modal" role="dialog" aria-modal="true" aria-labelledby="connector-detail-title"><div className="settings-panel-heading"><div><h3 id="connector-detail-title">{connector.name}</h3><p>{connector.description}</p></div><button type="button" className="settings-close" aria-label="Close connector details" onClick={onClose}>×</button></div>{error && <p className="settings-status settings-error" role="alert">{error}</p>}<div className="connector-detail-section"><div className="connector-detail-heading"><h4>Accounts</h4><button type="button" className="settings-save" disabled={busy || connector.provider !== "managed"} onClick={() => void connect()}>{busy ? "Working…" : "Connect account"}</button></div>{connections.length ? connections.map((connection) => <div className="connector-account-row" key={connection.id}><span><strong>{connection.accountLabel ?? connection.accountEmail ?? "Connected account"}</strong><small>{connection.accountEmail ?? ""} · {connection.status === "reconnect_required" ? "Reconnect required" : connection.status}</small></span><span className="connector-account-actions">{connection.isDefault ? <small>Default</small> : <button type="button" className="settings-cancel" disabled={busy} onClick={() => void setDefaultConnectorConnection(connector.id, connection.id).then(onChanged).catch((reason) => setError(reason instanceof Error ? reason.message : "Account could not be selected."))}>Use by default</button>}<button type="button" className="settings-cancel" disabled={busy} onClick={() => void refresh(connection.id)}>Refresh tools</button><button type="button" className="settings-cancel" disabled={busy} onClick={() => void disconnect(connection.id)}>Disconnect</button></span></div>) : <p className="settings-status">No accounts connected.</p>}</div><ConnectorPermissions tools={tools} busy={busy} onChange={(tool, enabled) => void changeTool(tool, enabled)} onApprovalChange={(tool, mode) => void changeApproval(tool, mode)} />{connector.provider === "remote_mcp" && <button type="button" className="settings-cancel connector-remove" disabled={busy} onClick={() => void remove()}>Remove MCP server</button>}<div className="settings-actions"><button type="button" className="settings-cancel" onClick={onClose}>Done</button></div></section></div>;
}
