import "server-only";
import { DOCUMENT_SOURCE_BUCKET, validateDocumentProjectManifest, type DocumentProjectManifestV1 } from "../../../lib/document-project";
import { getServerClient } from "../../auth/supabase-server-adapter";

type Db = ReturnType<typeof getServerClient>;
// Supabase's fluent builder changes its generic result type at each filter;
// this helper deliberately preserves that library-owned builder type.
// eslint-disable-next-line @typescript-eslint/no-explicit-any
const scope = (query: any, input: { ownerId: string; conversationId: string; projectId: string }) => query.eq("owner_id", input.ownerId).eq("conversation_id", input.conversationId).eq("project_id", input.projectId);
export function revisionSourceStoragePath(input: { ownerId: string; conversationId: string; projectId: string; revisionId: string; relativePath: string }) { return `${input.ownerId}/${input.conversationId}/${input.projectId}/${input.revisionId}/${input.relativePath}`; }
export function createDocumentProjectStore(db: Db = getServerClient()) {
  return {
    async createProject(input: { ownerId: string; conversationId: string; projectId: string; title: string; origin?: "generated" | "uploaded" }) { const { error } = await db.from("chat_document_projects").insert({ owner_id: input.ownerId, conversation_id: input.conversationId, project_id: input.projectId, title: input.title, origin: input.origin ?? "generated" }); if (error) throw error; },
    async registerRevision(input: { ownerId: string; conversationId: string; manifest: DocumentProjectManifestV1; renderedDocumentId: string }) { const m = validateDocumentProjectManifest(input.manifest); const { error } = await db.from("chat_document_revisions").insert({ owner_id: input.ownerId, conversation_id: input.conversationId, project_id: m.projectId, revision_id: m.revisionId, parent_revision_id: m.parentRevisionId, rendered_document_id: input.renderedDocumentId, entrypoint: m.entrypoint, output_path: m.outputPath, output_filename: m.outputFilename, output_content_type: m.outputContentType, output_sha256: m.outputSha256, source_completeness: m.sourceCompleteness, manifest: m, status: "creating", created_by_job_id: m.createdByJobId }); if (error) throw error; },
    async uploadSourceFiles(input: { ownerId: string; conversationId: string; manifest: DocumentProjectManifestV1; files: Map<string, Uint8Array> }) { for (const file of input.manifest.sourceFiles) { const bytes = input.files.get(file.path); if (!bytes) throw new Error(`Missing captured source file: ${file.path}`); const storagePath = revisionSourceStoragePath({ ...input, projectId: input.manifest.projectId, revisionId: input.manifest.revisionId, relativePath: file.path }); const { error: uploadError } = await db.storage.from(DOCUMENT_SOURCE_BUCKET).upload(storagePath, bytes, { contentType: file.contentType, upsert: false }); if (uploadError) throw uploadError; const { error } = await db.from("chat_document_revision_files").insert({ owner_id: input.ownerId, conversation_id: input.conversationId, project_id: input.manifest.projectId, revision_id: input.manifest.revisionId, relative_path: file.path, storage_path: storagePath, content_type: file.contentType, size: file.size, sha256: file.sha256 }); if (error) throw error; } },
    async finalizeRevision(input: { ownerId: string; conversationId: string; projectId: string; revisionId: string }) { const { error } = await scope(db.from("chat_document_revisions").update({ status: "complete" }), input).eq("revision_id", input.revisionId).eq("status", "creating"); if (error) throw error; },
    async markRevisionFailed(input: { ownerId: string; conversationId: string; projectId: string; revisionId: string }) { const { error } = await scope(db.from("chat_document_revisions").update({ status: "failed" }), input).eq("revision_id", input.revisionId); if (error) throw error; },
    async getRevision(input: { ownerId: string; conversationId: string; projectId: string; revisionId: string }) { const { data, error } = await scope(db.from("chat_document_revisions").select("*"), input).eq("revision_id", input.revisionId).maybeSingle(); if (error) throw error; return data; },
    async listRevisionFiles(input: { ownerId: string; conversationId: string; projectId: string; revisionId: string }) { const { data, error } = await scope(db.from("chat_document_revision_files").select("relative_path,storage_path,content_type,size,sha256"), input).eq("revision_id", input.revisionId); if (error) throw error; return data ?? []; },
    async downloadRevisionSourceFile(input: { ownerId: string; conversationId: string; projectId: string; revisionId: string; relativePath: string }) { const { data: row, error } = await scope(db.from("chat_document_revision_files").select("storage_path"), input).eq("revision_id", input.revisionId).eq("relative_path", input.relativePath).maybeSingle(); if (error) throw error; if (!row) return null; const result = await db.storage.from(DOCUMENT_SOURCE_BUCKET).download(row.storage_path); if (result.error) throw result.error; return new Uint8Array(await result.data.arrayBuffer()); },
  };
}
